export const SET_CRYPTO_DATA = "SET_CRYPTO_DATA";
export const ADD_CRYPTO_DATA = "ADD_CRYPTO_DATA";
export const SHOW_CRYPTO_DATA_DISPLAY = "SHOW_CRYPTO_DATA_DISPLAY";
export const GET_CRYPTO_PRICE_HISTORY = "GET_CRYPTO_PRICE_HISTORY";
export const GET_ALL_USERS = "GET_ALL_USERS";
export const GET_USER_BY_ID = "GET_USER_BY_ID";
export const ADD_CRYPTO_DATA_TO_USER_COLLECTION = "ADD_CRYPTO_DATA_TO_USER_COLLECTION";