export const SET_CRYPTO_DATA = "SET_CRYPTO_DATA";
export const ADD_CRYPTO_DATA = "ADD_CRYPTO_DATA";
export const SHOW_CRYPTO_DATA_DISPLAY = "SHOW_CRYPTO_DATA_DISPLAY"
export const GET_CRYPTO_PRICE_HISTORY = "GET_CRYPTO_PRICE_HISTORY"